services:
  question-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: question-service
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_credentials.json
      USER_SERVICE_URL: http://user-service:3002
      PORT: 3001
    secrets:
      - gcp_credentials.json
    ports:
      - 3001:3001
    expose:
      - 3001
    networks:
      - demo-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_credentials.json
      JWT_SECRET_PATH: /run/secrets/jwt_secret
      PORT: 3002
    secrets:
      - gcp_credentials.json
      - jwt_secret
    ports:
      - 3002:3002
    expose:
      - 3002
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

secrets:
  gcp_credentials.json:
    file: ./service-account.json
  jwt_secret:
    file: ./jwt_secret.txt
